apiVersion: v1
kind: Pod
metadata:
  name: db-blog
  namespace: labwordpress
  labels:
    app: db-blog
spec:
  containers:
    - name: db-blog-container
      image: mysql
      ports:
        - containerPort: 3308
      envFrom: 
        - configMapRef:
            name: db-configmap