apiVersion: v1
kind: Service
metadata:
  name: svc-blog-grupo3
  namespace: labwordpress
  labels:
  app: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
        protocol: TCP
  selector:
    app: blog-grupo3
    tier: frontend
