apiVersion: v1
kind: Service
metadata:
  name: svc-blog-grupo3
  namespace: labwordpress
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: blog-grupo3